//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMWP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AMWPEntities : DbContext
    {
        public AMWPEntities()
            : base("name=AMWPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Cash> Cash { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Currencies> Currencies { get; set; }
        public virtual DbSet<Daily> Daily { get; set; }
        public virtual DbSet<Managements> Managements { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Monthly> Monthly { get; set; }
        public virtual DbSet<Properties> Properties { get; set; }
        public virtual DbSet<SecOrders> SecOrders { get; set; }
        public virtual DbSet<SecTypes> SecTypes { get; set; }
        public virtual DbSet<Securities> Securities { get; set; }
        public virtual DbSet<Weekly> Weekly { get; set; }
    }
}
